import os
from glob import glob

############################################
# --------------- CONFIG -------------------
############################################

# Paths relative to scripts/gene_level/ (the Snakemake invocation cwd).
# Outputs land under <repo>/output/gene_level/<chr>/<gene>/.
SNAPTRON_BASE = "../../data/all_genes"
OUTPUT_BASE   = "../../output/gene_level"

# Script
SCRIPT1 = "gene_plots_and_objs.R"

# Outputs (per gene)
OUTPUT1_SUFFIXES = ["res.RDS", "de_res.RDS", "whole_factor.html"]

# Static inputs (under data/ at the repo root)
GENCODE       = "../../data/hg38_granges.RDS"
TCGA_METADATA = "../../data/tcga_v2_samples.tsv"

# Resources
THREADS = 10

# Factorization thresholds
ELBOW_CUTOFF = 0.01
MAX_FACTORS  = 10
LFC_THRESH   = 2
ABS_THRESH   = 0.01
SVAL_THRESH  = 0.05

# dat-generation parameters (from R script comments)
MIN_JUNCTIONS_FOR_PCA        = 3
GENE_RANGE_BOUND             = 2000
AVG_CLUST_READ_COUNT_MIN     = 0
MIN_SAMPLES_PER_JUNC         = 10
AVG_SAMPLE_READS_PER_CLUSTER = 5


############################################
# -------- SNAPTRON-BASED DISCOVERY --------
############################################

def get_genes():
    genes = []
    for chr_dir in sorted(glob(os.path.join(SNAPTRON_BASE, "chr*"))):
        chr_name = os.path.basename(chr_dir)
        snaptron_dir = os.path.join(chr_dir, "snaptron_output")

        if not os.path.isdir(snaptron_dir):
            continue

        for snaptron_file in sorted(glob(os.path.join(snaptron_dir, "*_snaptron.tsv"))):
            if os.path.getsize(snaptron_file) < 100:
                continue

            gene_name = os.path.basename(snaptron_file).replace("_snaptron.tsv", "")
            genes.append((chr_name, gene_name))

    return genes


GENE_INFO = get_genes()

GENE_OUTPUTS = [
    f"{OUTPUT_BASE}/{chr}/{gene}/{suffix}"
    for chr, gene in GENE_INFO
    for suffix in OUTPUT1_SUFFIXES
]


############################################
# ---------------- RULES -------------------
############################################

rule all:
    input:
        GENE_OUTPUTS


############################################
# Gene plots + objects (Snaptron -> NMF)
############################################

rule run_gene_plots_and_objs:
    input:
        snaptron=SNAPTRON_BASE + "/{chr}/snaptron_output/{gene}_snaptron.tsv"
    output:
        res          = OUTPUT_BASE + "/{chr}/{gene}/res.RDS",
        de_res       = OUTPUT_BASE + "/{chr}/{gene}/de_res.RDS",
        whole_factor = OUTPUT_BASE + "/{chr}/{gene}/whole_factor.html"
    params:
        # dat-generation params
        min_junctions_for_pca        = MIN_JUNCTIONS_FOR_PCA,
        gene_range_bound             = GENE_RANGE_BOUND,
        avg_clust_read_count_min     = AVG_CLUST_READ_COUNT_MIN,
        min_samples_per_junc         = MIN_SAMPLES_PER_JUNC,
        avg_sample_reads_per_cluster = AVG_SAMPLE_READS_PER_CLUSTER,

        # factorization params
        gencode        = GENCODE,
        tcga_metadata  = TCGA_METADATA,
        threads        = THREADS,
        elbow_cutoff   = ELBOW_CUTOFF,
        max_factors    = MAX_FACTORS,
        lfc_thresh     = LFC_THRESH,
        abs_thresh     = ABS_THRESH,
        sval_thresh    = SVAL_THRESH,
        script         = SCRIPT1,
        output_base    = OUTPUT_BASE
    conda:
        "envs/rscript.yml"
    threads: 10
    resources:
        mem_mb=10000
    shell:
        """
        set -euo pipefail
        mkdir -p {params.output_base}/{wildcards.chr}/{wildcards.gene}

        Rscript {params.script} \
            {params.min_junctions_for_pca} \
            {params.gene_range_bound} \
            {params.avg_clust_read_count_min} \
            {input.snaptron} \
            {params.min_samples_per_junc} \
            {params.avg_sample_reads_per_cluster} \
            {wildcards.gene} \
            {wildcards.chr} \
            {params.gencode} \
            {params.tcga_metadata} \
            {params.threads} \
            {params.elbow_cutoff} \
            {params.max_factors} \
            {params.lfc_thresh} \
            {params.abs_thresh} \
            {params.sval_thresh} \
            {params.output_base}
        """
